name: dockerbuild

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v2

      - name: build
        run: ./build.sh; pwd; ls

      - name: generate tag
        run: |-
          export PROJ_VERSION="1.0.2"
          echo "Project Version: $PROJ_VERSION"
          echo "TAG=$PROJ_VERSION-$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "SHORT_TAG=$PROJ_VERSION" >> $GITHUB_ENV

      
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.OU_REG_USER }}
          password: ${{ secrets.OU_REG_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        
        with:
          push: true
          context: "."
          platforms: linux/amd64,linux/arm64
          dockerFile: "./DockerFile"
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.TAG }}
            ghcr.io/${{ env.REPO }}:${{ env.SHORT_TAG }}
            ghcr.io/${{ env.REPO }}:latest
            
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-k8s-react:${{ env.TAG }}
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-k8s-react:${{ env.SHORT_TAG }}
            docker.io/${{ secrets.OU_CONTAINER_REPO }}/openunison-k8s-react:latest

            
            
            
            
            
          
